### ISSUE TITLE
Players move at twice normal speed when moving at a 45 degree angle.

### ISSUE THREAD

**Issue by HugoCortell** [ExtendRealityLtd/Tilia.Locomotors.AxisMove.Unity#14] opened 2020-07-08 00:15 UTC
### Environment

* Code source: I got it from the manifest.json
* Code version: 1.1.4
* Platform version: 2019.4.1f1
* 3rd party dependencies: None I think idk iv got near all other packages

### Steps to reproduce

1. Set up the player with axis move like you would in the brain dump.
2. Make a plain for the player to walk on
3. (HTC) Place your finger at a 45 degree angle to move at twice normals speed.

### Expected behavior

Player moves at the desired speed.

### Current behavior

High Speed and high chances of acid reflux.

# I made a recording where I show it.
There are two bugs, you can download both or just the zip file related to this bug.
https://gofile.io/d/Md7uEl

**Comment by thestonefox** [comment] 2020-07-08 06:26
Your axis sensitivity is too low in your input settings.

Set your axis4 and axis5 sensitivity to `3`

![image](https://user-images.githubusercontent.com/1029673/86885004-648d0600-c0ec-11ea-98ab-00f453a35077.png)

**Comment by HugoCortell** [comment] 2020-07-10 00:15
I set it to different sensitivities.
3, 15, 999 and 9999. None of them showed any improvement.

**Comment by fight4dream** [comment] 2020-07-10 07:27
Code version: 1.1.4
Platform version: 2019.4.1f1
with the new tilia input axis sensitivities

setup A:
1. using Locomotors.AxisMove.Vertical-Slide.Horizontal-Slide
2. make two float actions (horizontal axis, vertical axis). do not hook up sources. e.g.
![image](https://user-images.githubusercontent.com/22952143/87127318-52fc5780-c2c0-11ea-8c6c-fbe88fa5a017.png)
3. our axis move will use these 2 axes, target is PlayAreaAlias
![image](https://user-images.githubusercontent.com/22952143/87127419-76bf9d80-c2c0-11ea-8789-9962cd1bcd00.png)
4. using left track pad horizontal axis, call from Value Changed and Value Unchanged feed it into horizontal axis. do the same for vertical axis (notice the Logger is to print out the value for debug. confirmed that pressing the trackpad top-right corner will receive (<0.707, <0.707). for example usually up to (0.66, 0.66)
![image](https://user-images.githubusercontent.com/22952143/87127539-a373b500-c2c0-11ea-85d7-85b25c5c1da7.png)
5. test moving purely horizontal/vertical. then test moving diagonally.

current behaviour:
diagonally will move significantly faster

setup B: (as a control)
same step 1 to 3 as in setup A
4. we will then set up 9 keypad inputs.
![image](https://user-images.githubusercontent.com/22952143/87127989-77a4ff00-c2c1-11ea-8603-3bc2cc2a89d7.png)
the name reflects the intention of the key. e.g.  [3] h+0.707 v-0.707 means when keypad num 3 activates, horizontal axis receives +0.707, vertical axis receives -0.707
![image](https://user-images.githubusercontent.com/22952143/87128184-c5ba0280-c2c1-11ea-8bb8-0d1f50a41643.png)
5. test moving purely horizontal/vertical. then test moving diagonally.

current behaviour:
notice that diagonally will NOT move significantly faster

**Comment by thestonefox** [comment] 2020-07-10 07:28
What hardware are you testing on?

**Comment by fight4dream** [comment] 2020-07-10 07:29
in the above setups, i chose not to use the 'Sources' to minimize possible logic errors.

PC, HTC Vive

i will do the setup A test on Quest in a moment

**Comment by thestonefox** [comment] 2020-07-10 07:30
I tried on Rift S on PC with sensitivity of 3 and I noticed a massive change and there was no speed increase.

**Comment by thestonefox** [comment] 2020-07-10 07:31
what's the magnitude of the directional vector? i noticed on the Rift S if the sensitivity was too low then it would never exceed 1

**Comment by fight4dream** [comment] 2020-07-10 07:35
vive trackpad is designed to receive values (h,v) within a unit circle. it IS correct the inputs never exceed 1

**Comment by thestonefox** [comment] 2020-07-10 07:38
I think the issue on the Rift S may have been if the sensitivity was too low then it would fire the axis events multiple times, so if you pressed up it would fire up, if you pressed left it would fire left

but if you pressed up and left it would fire up, up left, up up left left

which is why the speed increased because I noticed very little difference in the output value (was always 0.7, 0.7)

**Comment by fight4dream** [comment] 2020-07-10 07:47
you can confirm your multiple event hypothesis by testing in setup A,
your Logger
```
    public void Log(float value)
    {
        if (isActiveAndEnabled)
        {
            Debug.Log($"{Time.frameCount} {value:.00}");
        }
    }
```

**Comment by fight4dream** [comment] 2020-07-10 07:50
confirmed on Quest is the same. the diagonal direction is faster.

**Comment by thestonefox** [comment] 2020-07-10 07:53
Can you try in an older version of unity? I was testing in 2018.3.14

**Comment by thestonefox** [comment] 2020-07-10 07:57
Also, confirm which controller you are using to test on? Left, Right, or Both? and is there any known difference on both?

**Comment by fight4dream** [comment] 2020-07-10 08:04
![image](https://user-images.githubusercontent.com/22952143/87130973-51359280-c2c6-11ea-8bfa-a735abcc5328.png)
printing all value changed and value unchanged events.
notice the same framecount appear twice because i'm printing both horizontal and vertical.
also the Unity button action is based on Update(). so it basically disprove your hypothesis that some events are fired multiple time because even it changed multiple time within same frame, we only fetch once for each axis

**Comment by thestonefox** [comment] 2020-07-10 08:08
Ok on the Rift S in 2018.3.14f1 using the right controller:

Tilia packages:

![image](https://user-images.githubusercontent.com/1029673/87131769-c8e6cb80-c28c-11ea-82b2-041c9f098841.png)

Sensitivity set to 1:

![image](https://user-images.githubusercontent.com/1029673/87131782-d00dd980-c28c-11ea-8e76-10aa9d6410c4.png)


Result:

Clear speed up:

![rifts-1](https://user-images.githubusercontent.com/1029673/87131795-d7cd7e00-c28c-11ea-900a-0d059a89db95.gif)


Sensitivity set to 3:

![image](https://user-images.githubusercontent.com/1029673/87131809-de5bf580-c28c-11ea-922e-ce20bb8b33eb.png)

Result:

No Speed up:

![rifts-3](https://user-images.githubusercontent.com/1029673/87131825-e61b9a00-c28c-11ea-9543-4771270dfab2.gif)

**Comment by thestonefox** [comment] 2020-07-10 08:12
Are you running through SteamVR?

**Comment by fight4dream** [comment] 2020-07-10 08:12
htc vive, steamVR, unity XR, Left wand

**Comment by fight4dream** [comment] 2020-07-10 08:13
however for Quest , i purely built on Quest and not through PC. Left controller, sensitivity already is 3.

**Comment by thestonefox** [comment] 2020-07-10 08:14
Well as you can see from my above tests, there's no speed increase for me, I tried just on SteamVR too and still no increase (on right controller)

**Comment by fight4dream** [comment] 2020-07-10 08:15
i'll test on the right.
can you test on the left?

**Comment by thestonefox** [comment] 2020-07-10 08:18
haha, looks like Unity override the sensitivity settings on the left as it's just using `Horizontal` and `Vertical`

The ones at the the top use 3 but the lower ones override it back to 1

![image](https://user-images.githubusercontent.com/1029673/87132757-3f37fd80-c28e-11ea-9cf9-71338788a96d.png)


Change both to 3

**Comment by fight4dream** [comment] 2020-07-10 08:27
my right controller is very wrong. the vertical axis is flipped

**Comment by fight4dream** [comment] 2020-07-10 08:28
also it even has input (-1, .99) which should not be possible (magnitude > 1, not within the unit circle)

**Comment by thestonefox** [comment] 2020-07-10 08:29
Yeah that's a bug in Tilia UnityInput on the OVRController, the axis multiplier on the vertical is set to -1

just change it to 1 for now (i'll fix it in the repo)

![image](https://user-images.githubusercontent.com/1029673/87133820-c76ad280-c28f-11ea-9dde-e312ff1f96ab.png)

**Comment by fight4dream** [comment] 2020-07-10 08:33
multiplier 1 -> fixed the flipping.
but still, seems the sensitivity =3 directly multiply the input by 3 and then clamp at [0,1] range.
hence i received the non-unit circle inputs
and still, the diagonal is speed up (because walk +1/s in horizontal and +1/s in vertical = +1.414/s

**Comment by thestonefox** [comment] 2020-07-10 08:34
I'm not getting that on the left controller with the Rift S even when using SteamVR

**Comment by fight4dream** [comment] 2020-07-10 08:35
what are your inputs received when you log them?

**Comment by thestonefox** [comment] 2020-07-10 08:43
What logging are you doing? The one from the logger script above?

also did you change all of the settings in the second horizontal/vertical (including the deadzone to 0.001)?

**Comment by fight4dream** [comment] 2020-07-10 08:43
> you can confirm your multiple event hypothesis by testing in setup A,
> your Logger
> 
> ```
>     public void Log(float value)
>     {
>         if (isActiveAndEnabled)
>         {
>             Debug.Log($"{Time.frameCount} {value:.00}");
>         }
>     }
> ```

**Comment by fight4dream** [comment] 2020-07-10 08:44
whatever the input is , directly print it out
i'm outputing both horizontal and vertical axis inputs

**Comment by fight4dream** [comment] 2020-07-10 08:44
i'm now making ALL axis sensitivity back to 1, deadzone also should be 0.001

**Comment by thestonefox** [comment] 2020-07-10 08:45
Not sure how useful this info is:
![image](https://user-images.githubusercontent.com/1029673/87135471-fbdf8e00-c291-11ea-9824-e3f4ca2d9190.png)

**Comment by fight4dream** [comment] 2020-07-10 08:46
value unchanged also

**Comment by thestonefox** [comment] 2020-07-10 08:48
![image](https://user-images.githubusercontent.com/1029673/87135843-8627f200-c292-11ea-85e2-fa9ca8352dcc.png)

**Comment by fight4dream** [comment] 2020-07-10 08:50
for example in your log,
195 -.86
195 1.00
meaning (-.86, 1.00). this is outside of the unit circle.
this is the result of sensitivity = 3

**Comment by thestonefox** [comment] 2020-07-10 08:51
But I get no speed up, so what's the problem now?

**Comment by fight4dream** [comment] 2020-07-10 08:52
please change back to sensitivity=1 .  the input should be within the unit circle.
and test your rift S left controller because you somehow think its input is too small so your bump up the sen
which i think was not correct

**Comment by fight4dream** [comment] 2020-07-10 08:54
study carefully of my report. SETUP A has speed up. SETUP B has no speed up.
i also do not understand why it is so. they seemingly should behave identically. but they are not.
so it is very possible your setup somehow is luckily has no speed up

**Comment by thestonefox** [comment] 2020-07-10 08:55
I think we may be veering off the subject of this issue.

This issue is about the speed up of the axis move. setting sensitivity to 3 seems to fix that for me.

If having sensitivities over 3 is causing another issue then I think that should be raised as a new issue and not be related to axis move.

**Comment by fight4dream** [comment] 2020-07-10 09:00
i've to disagree to the insistant of sen 3
look, all i'm doing in SETUP B is to make sure my keypad can mimic the absolute correct input on a unit circle
which is ideally 1unit movement per timeunit velocity in ANY direction.

with sen 3. clearly your log state that it will become a square with length 2 (-1,-1) to (1,1)
and we know that the diagonal direction, its magnitude is thus 1.414 .
IF your axis move works absolutely correctly that it will translate the play area by the combined axis amount
the unit circle inputs will make sure it moves the same unit in all direction,
the square inputs will make it speed up in diagonal direction.

hence, it is very relevant to not set the sen to 3 to isolate the problem to only axis move (and i assume it is your malfunction rift s left controller instead)

**Comment by thestonefox** [comment] 2020-07-10 09:04
There is no malfunction in either my left or right Rift S controller, they are both operating normally.

I'm not disputing a sensitivity of 3 isn't going to cause a different issue somewhere else, BUT setting the sensitivity to 3 DOES solve the speed up in diagonal issue for me.

If someone needs a quick fix and are happy with this then it should also work for them.

If we can identify where the issue of having a sensitivity of 3 will present itself then that should be discussed in another thread.

If that ends up with a fix that allows the sensitivity to be set back to 1, then we can update this issue at that point.

**Comment by fight4dream** [comment] 2020-07-10 09:09
at the moment, at least both me and hugo with sen 3 does not fix our issues.

**Comment by thestonefox** [comment] 2020-07-10 09:17
Have you updated your sensitivity in both places and tried on both controllers in Unity 2018.3.14?

We also don't know if Hugo has also done the above steps.

Also, just as a side test, on an xbox controller even on sensitivity 1 you get no speed up using the analog sticks

**Comment by fight4dream** [comment] 2020-07-10 09:17
yes i'm downgrading for a test :)

**Comment by thestonefox** [comment] 2020-07-10 09:18
i've even tried normalizing/clamping magnitude of the input (and final movement vector) and neither work (plus they trim off your corners so you can't move in a slight diagonal way)

**Comment by fight4dream** [comment] 2020-07-10 09:19
have you checked your Horizontal/Vertical deadzones are 0.001 ?

**Comment by thestonefox** [comment] 2020-07-10 09:21
Yeah they're 0.001 in the input manager

**Comment by fight4dream** [comment] 2020-07-10 09:21
may i have a moment with you on discord? dm

**Comment by xand7** [comment] 2020-07-10 09:21
Hello there,

I'm encountering the same issue, except my circumstances are slightly different.  My axis input is hooked up to SteamVR horizontal/vertical inputs.  I'm using an Index with the left controller on Unity 2019.3.4.

**Comment by fight4dream** [comment] 2020-07-10 09:24
hi xand7.
we will be testing under the sensitivity=3, deadzone=0.001 settings in case of any confusion.
1. if you hook up to right controller, is it also having the speed up issue?
2. can you also test with 2018.3.14 ?

**Comment by xand7** [comment] 2020-07-10 09:28
I might be misunderstanding but I thought the sensitivity and deadzone settings discussed here applied to the Unity inputs used with the Tilla OpenVR controller prefabs.  I'm not using those at all, for me those settings I think will be coming from the SteamVR I think?  I will have a play around with those settings in the SteamVR input widget to see if it makes any difference.

Will attempt to see if things are the same for Right controller.

I have 2018.3.7 so could potentially test with that.

**Comment by thestonefox** [comment] 2020-07-10 09:29
@xand7 if you have a different set up then please list what your exact set up is

**Comment by xand7** [comment] 2020-07-10 09:36
I'm not sure exactly what information would be pertinent beyond what I've already stated.  I'm using the STEAMVR input manager to create actions.  I have an action for horizontal and vertical stick movement in the steamvr input manager.  In the project I have the following script:

![image](https://user-images.githubusercontent.com/17430635/87140190-05b8bf80-c299-11ea-968d-e5e5ff36b09e.png)

Taking the STEAMVR input and sending it to the Zinnia float action for either horizontal or vertical axis input.

These float actions are those being used here:

![image](https://user-images.githubusercontent.com/17430635/87140288-300a7d00-c299-11ea-99b6-0ecc1da65c5b.png)

**Comment by thestonefox** [comment] 2020-07-10 10:16
Can someone try simply setting the deadzone settings to 0 in the `Internal -> MovementMutator -> InputAxis`

![image](https://user-images.githubusercontent.com/1029673/87143883-c7260380-c29e-11ea-91b7-67bb29427f24.png)

**Comment by xand7** [comment] 2020-07-10 10:20
Yup that resolved the issue for me thanks!

**Comment by thestonefox** [comment] 2020-07-10 10:23
Ok great, so its something to do with the deadzone calculations then

**Comment by fight4dream** [comment] 2020-07-10 10:24
mind blown

**Comment by thestonefox** [comment] 2020-07-10 10:24
And this is why you dont see the problem on keyboard because you tend never to drop below the deadzone

0.7, 0.7 is always above the deadzone.

I think the problem is the deadzone calculation is saying

if you're pressing fully up but just a bit right (e.g. 0.1, 1) then ignore the right push because you're not in the deadzone, which i think is wrong.

**Comment by xand7** [comment] 2020-07-10 10:30
I see.  Thanks for the help looking into this.

**Comment by fight4dream** [comment] 2020-07-10 10:34
i'll test more under this setup. the vive pad cannot easily be touched and receive on unit circle values

**Comment by fight4dream** [comment] 2020-07-10 10:50
seems correct if axis move deadzone 0.
i wanted to test the original deadzone again, but when i hit play, the deadzone values is reverted to 0

**Comment by thestonefox** [comment] 2020-07-10 10:51
I know the issue. I'm raising a bug on CombinedActions for it

**Comment by fight4dream** [comment] 2020-07-10 10:53
thx. i managed to set it back to original (-0.5,0.5) deadzone and confirmed the speed up (or rather, the 'pure' direction is slowed down)
then now to (0) deadzone, it is uniform in all direction

**Comment by thestonefox** [comment] 2020-07-10 10:58
I'm going to close this issue and relate to the underlying deadzone issue here:

https://github.com/ExtendRealityLtd/Tilia.Input.CombinedActions.Unity/issues/21

**Closed by thestonefox** 2020-07-10 10:58 UTC
